// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDSmGb3VPEceeG4tDLFISelJVOP-RWOG0',
    appId: '1:965609283116:web:71df525fadefce69effb89',
    messagingSenderId: '965609283116',
    projectId: 'licesea',
    authDomain: 'licesea.firebaseapp.com',
    databaseURL: 'https://licesea-default-rtdb.firebaseio.com',
    storageBucket: 'licesea.appspot.com',
    measurementId: 'G-G7X6GB8SXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQ7sOzMqghi1ZkgbV30xBGYA3Bkz8tQs',
    appId: '1:965609283116:android:eac3ca22bc6e2b10effb89',
    messagingSenderId: '965609283116',
    projectId: 'licesea',
    databaseURL: 'https://licesea-default-rtdb.firebaseio.com',
    storageBucket: 'licesea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARxpLn8GXO9cKjVq_eExhxYJPvR_Ce5hg',
    appId: '1:965609283116:ios:e7f4956b133d87a3effb89',
    messagingSenderId: '965609283116',
    projectId: 'licesea',
    databaseURL: 'https://licesea-default-rtdb.firebaseio.com',
    storageBucket: 'licesea.appspot.com',
    iosBundleId: 'com.example.licensea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARxpLn8GXO9cKjVq_eExhxYJPvR_Ce5hg',
    appId: '1:965609283116:ios:e7f4956b133d87a3effb89',
    messagingSenderId: '965609283116',
    projectId: 'licesea',
    databaseURL: 'https://licesea-default-rtdb.firebaseio.com',
    storageBucket: 'licesea.appspot.com',
    iosBundleId: 'com.example.licensea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDSmGb3VPEceeG4tDLFISelJVOP-RWOG0',
    appId: '1:965609283116:web:9f61f04aa4350452effb89',
    messagingSenderId: '965609283116',
    projectId: 'licesea',
    authDomain: 'licesea.firebaseapp.com',
    databaseURL: 'https://licesea-default-rtdb.firebaseio.com',
    storageBucket: 'licesea.appspot.com',
    measurementId: 'G-0BQYPDGGE3',
  );

}